spring:
  thymeleaf:
    prefix                 : classpath:templates/
    suffix                 : .html
    mode                   : HTML5
    cache                  : false
    check-template-location: true
    
  datasource:
    driver-class-name      : com.mysql.jdbc.Driver
    url                    : jdbc:mysql://cyclo79.cafe24.com:3306/cyclo79?verifyServerCertificate=false&useSSL=false&serverTimeZone=UTC&characterEncoding=EUC-KR
    username               : cyclo79
    password               : cho3233